### ISSUE TITLE
Multi-dimensional arrays with unknown size

### ISSUE THREAD

**Issue by VVWVV** [Zeex/pawn#137]
Access to arrays with unknown size doesn't work correctly:
````pawn
static some_array[][] = {
     {1,2},
     {3,4,5,6}
};
````

```pawn
main() {
     printf("Result: %d", some_array[0][4]);
}
````

**Result:**
```shell
Result: 5
````

**Comment by Y-Less** [comment]
That's an OOB, so undefined anyway.  The highest you can access legally is `[0][3]`.  However, if you array was slightly larger, this would be correct:

```pawn
static some_array[][] = {
     {1,2},
     {3,4,5,6,7}
};
```

Should be detected by the compiler as:

```pawn
static some_array[2][5] = {
     {1,2},
     {3,4,5,6,7}
};
```

(if you can disprove that, that's a more serious problem).

The first index doesn't have all its values specified so they are interpolated as:

```pawn
static some_array[2][5] = {
     {1,2,3,4,5},
     {3,4,5,6,7}
};
```

Thus `some_array[0][4]` will print `5`.  Your missing piece of information might be the fact that the compiler interpolates instead of zeros unspecified values.  However, this interpolation often results in 0 if nothing is specified.  See this for an example:

https://github.com/Misiur/YSI-Includes/blob/7c9fa55fbe8411ad3db18f2417e6a01811b820b8/YSI_Data/y_foreach/impl.inc#L229

**Comment by VVWVV** [comment]
@Y-Less, but the compiler does not give an error, i.e. `some_array[0][4]` is legally.
````pawn
static some_array[][] = {
     {1,2},
     {3,4,5,6}
};
````
And the compiler generates (in ASM):
````
DATA 0	; 0
dump 8 c 1 2 3 4 5 6
````
As you can see, the compiler does not interpolate anything.

**Comment by Y-Less** [comment]
Ahh yes, that is wrong.  Your post was misleading because you used the same values as the compiler would have guessed.

**Comment by YashasSamaga** [comment]
Did it really give the output as 8 c? The first dimension has two elements, so the c should've been 0x10 I guess.

**Comment by Y-Less** [comment]
Actually, no, I was right!  You are accessing an OOB index as I said, so anything you do is liable to give the wrong answer, as it has here.  Yashas pointed out something I didn't notice initally:

Array data:

```
8 c 1 2 3 4 5 6
```

Index 0 (0 bytes) + 8 bytes = index 2 (1)
Index 1 (4 bytes) + 12 bytes = slot 4 (3)

So the array is more compressed than I thought it would be, but correct for what you typed, and your problem as I said is that you are accessing data out of bounds.

**Comment by VVWVV** [comment]
Opss.. Yes, you were right!

If we use the arrays in which the dimensions of the elements are the same, the compiler is working correctly:
````pawn
static some_array[][] = {
     {-1,-6, 3, 4},
     {-1,-2,-3,-4}
};
````

```pawn
main() {
     printf("%d", some_array[0][0]);
     printf("%d", some_array[0][1]);
     printf("%d", some_array[0][2]);
     printf("%d", some_array[0][3]);
     printf("%d", some_array[0][4]);
     printf("%d", some_array[0][5]);
}
```

The compiler:
```shell
error 032: array index out of bounds (variable "some_array")
error 032: array index out of bounds (variable "some_array")
```

**Comment by Y-Less** [comment]
I didn't actually know the compiler compressed arrays like that though, so we both learned something!

**Comment by VVWVV** [comment]
I'll fix this problem.

**Comment by YashasSamaga** [comment]
An easy fix would be to disallow a minor index more than the size of the largest sub array but it will allow the following to be compiled without any warning:

```
static some_array[][] = {
     {1,2},
     {3,4,5,6}
};

some_array[0][3] = 5; //no error/warning
some_array[0][123] = 5; //error
```

**Comment by YashasSamaga** [comment]
I'll explain what the compiler is doing:
1. Reads the static/new/etc keyword (marks it for declaration)
2. Reads the symbol "some_array"
3. Reads the '[]' (now it knows that it is an array)
4. Attempts to read the indexes (if given, like [6])
5. Sees the '=' and initializes the array: reads the minor dimensions
6. Checks if the minor dimensions are equal. If they are equal, then it assumes that value as the minor dimension size. If the minor dimension sizes are not equal. It sets the size as 0 (used internally to mark arrays with variable size)
7. Dumps the data
8. Adds the array to the symbol table.  It is here where each sub array's size is set.

The compiler does count the number of elements in each array but it discards the count if they are not equal. Since it marks the sub-arrays' size not-a-fixed quantity (no size/variable), the compiler won't warn you when you use OOB index. The problem in fixing the bug is that a method has to be invented to store the count in step 6 so that it can be used in step 8. You can have up to `cellmax ` number of sub arrays, so to store the size of each sub-array, you will need an internal array which can hold `cellmax` entries. That array would take 16GB of memory.

**Comment by VVWVV** [comment]
Thanks. I knew about it.

**Comment by YashasSamaga** [comment]
This bug can do some amazing things.

http://forum.sa-mp.com/showpost.php?p=3849761&postcount=51
