### ISSUE TITLE
ignored constant sym param

### ISSUE THREAD

**Issue by Dayvison** [Zeex/pawn#159]
Code:
```c++
#if defined a
	#error "a"
#else
	#error "b"
#endif
main() { }
```
Command used:
`pawncc.exe m.pwn a=1`

Zeex compiler:
```
Pawn compiler 3.10.2                    Copyright (c) 1997-2006, ITB CompuPhase

m.pwn(4) : fatal error 111: user error: "b"


Compilation aborted.


1 Error.
```
Original compiler:
```
m.pwn(2) : fatal error 111: user error: "a"


Compilation aborted.

Pawn compiler 3.2.3664                  Copyright (c) 1997-2017, ITB CompuPhase


1 Error.
```

**Comment by YashasSamaga** [comment]
The compiler ignores constants which are passed as arguments. 

1. The compiler parses the compiler options at the very begining.
2. The compiler deletes the entire global symbol table before parsing.

So any constants which were added when the compiler options was being parsed is lost.

The bug is in the following line: https://github.com/Zeex/pawn/blob/master/source/compiler/sc1.c#L583

**Comment by Southclaws** [comment]
+1 I use this and I only found about this bug today, it would really screw up my build process if I migrated to this compiler (which I wanted to for SS).

@YashasSamaga could you submit a pull request with the proposed fix?
