### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Romz24** [Zeex/pawn#166]
Where can I see the instruction on how to install this compiler?

**Comment by Y-Less** [comment]
You literally just replace the old files with the new ones. There is no installer because there are no registry entries or complex directory structures to update. Copy and paste. However, if you put the word 'new' at the start of every filename in this version, you can use this script to quickly switch between the two versions:

https://gist.github.com/Y-Less/a51405ed79565dfbef7a

**Comment by Romz24** [comment]
What are these files for? "**/bin/pawndisasm.exe**" and "**/lib/pawnc.lib**"

**Comment by Y-Less** [comment]
The first one is a disassembler and can be ignored.  The second one, I'm not entirely sure, I think it is just a library used by the compiler, but there's no harm in just copying them all.

**Comment by Romz24** [comment]
- Why is the maximum length of the string **4095** and not **4096**? `#define sLINEMAX    4095`
- Will the compiler update in the future?
- I use stock which returns a value in float. It is at the end of my mod. And that there was no warning 208, I use forward. On the standard compiler everything is fine, but in this I still get warning 208, why? I know that this function can be declared at the beginning of the mod, but I do not want to do this.
`forward Float:GetPlayerDistanceFromPlayer(playerid, targetid);`
`stock Float:GetPlayerDistanceFromPlayer(playerid, targetid) { /**/ }`

**Comment by Y-Less** [comment]
- NULL terminators probably.
- Hopefully.
- Is the forward before the other functions?  That is the point - to tell the compiler what the return value of the function will be before you actually declare the function.  This is because `=` can be overloaded, so doing:

```pawn
x = Func();
```

Can generate different code depending on the return tag of `Func()`.  If the compiler knows in advance what that will be, it can generate the correct code the first time.  If it doesn't, it has to guess and just assumes integer (`_:`), then has to try again when it later finds out it was wrong.  If the forward or the function comes before the uses, there is no problem; if the function comes after and there is no forward, the compiler has to try twice (hence the warning); it sounds like you have the forward and the function after, which should generate the warning but probably didn't due to a since fixed bug.

**Comment by Zeex** [comment]
`pawnc.lib` was included in the Windows archive by mistake, you don't need to copy it. I'll look into that.

Other than that Y_Less pretty much answered everything, so closing this.
