### ISSUE TITLE
Unclear error (File paths)

### ISSUE THREAD

**Issue by rt-2** [Zeex/pawn#169]
Yeah... So i randomly got this error:
```
C:\Users\rt-2\Desktop\SAARP\SAMP\pawno\include\YSI\..\YSI_Coding\..\YSI_Core\y_utils.inc(254) : warning 202: number of arguments does not match definition
C:\Users\rt-2\Desktop\SAARP\SAMP\pawno\include\YSI\..\YSI_Coding\..\YSI_Core\y_utils.inc(267) : error 025: function heading differs from prototype
```
And I have no clue what file it is, what folder etc, so I can't even debug it.
Is there a way we could prevent file paths to be shorten?
Thank you,
rt-2

**Comment by Y-Less** [comment]
The file is y_utils.inc (as stated at the end of the long, admittedly odd, path).  The line is likely something to do with an `OnPlayerConnect` or `OnPlayerDisconnect` hook.  I can't be sure exactly, since it depends on which version of the file you have, but those are the only functions anywhere near that point.

**Comment by rt-2** [comment]
Yes I found out with commenting half of my file again and again that it was ``OnPlayerDisconnect`` the problem, but is there a way to avoid the compiler to shorten paths?
thank you,
rt-2

**Comment by Y-Less** [comment]
You mean make it shorten them?

**Comment by rt-2** [comment]
I'd like to see the full paths, is there an option, is it possible to toggle that?

**Comment by Y-Less** [comment]
That is the full path...

**Comment by rt-2** [comment]
My god, I tought the '..' were '...'.
You can't imagine how hard I tried to find what were the hidden folder,, then I realized it's just the 'parent folders'.
Thank you,
rt-2

**Comment by Y-Less** [comment]
I agree it could be shortened - print out just the fully rationalized path with parents removed.

**Comment by rt-2** [comment]
Its weird, but as long as the path is there (now I know), I don't know if this deserves much time of work.
rt-2

**Comment by Y-Less** [comment]
Probably worth leaving open though, just at least so it is a noted issue, even if not a high-priority one.  Just maybe also add a note to the first post summarising the discussion that the real problem is the lack of shrinking of the paths (in the display - they may need to be kept like that internally).

**Comment by rt-2** [comment]
Ok,
Thank you
