### ISSUE TITLE
[FEATURE REQUEST] "extern" keyword

### ISSUE THREAD

**Issue by YashasSamaga** [Zeex/pawn#217]
The extern keyword before a declaration tells the compiler that the definition is in some other file or will be defined somewhere below in the same file.

This allows more flexible ordering of includes and also reduces definition clutter at the top of every script.

**Comment by Y-Less** [comment]
I'm not sure what problem this solves.  Functions are already shared and globally available regardless of include order.  Variables should rarely be shared between files for better isolation and making bad practices easier is just bad.  The only thing this really affects is enums.

It also wouldn't really add anything for variables:

```pawn
extern gMyData;

Func()
{
    return gMyData;
}
```

Should this generate variable or array return code?  You can't tell from that, which means you need more information:

```pawn
extern gMyData[100][100];

Func()
{
    return gMyData;
}
```

Now the correct code is generated, but you have just as much clutter as you would have done with the declaration there in the first place, if not more:

```pawn
#if !defined ARR_SIZE
    #define ARR_SIZE (100)
#endif
extern gMyData[100][ARR_SIZE];

Func()
{
    return gMyData;
}
```

Now you need to manually check all requirements in all files, instead of just one.  I'm not sure why this is better than just:

```pawn
#include <other_file>

Func()
{
    return gMyData;
}
```

If a file uses something from another file, include that file in it.

And actually enums would have the same problem anyway:

```pawn
extern enum E_NUM;
static gVar[E_NUM];
Func()
{
    printf("%d", gVar[E_NUM_SLOT]);
}
```

How big is the variable?  Does the compiler need to come back and fill that out once it finally finds the enum?  Then go back and update every generated `BOUNDS` opcode and other use?  What does the line print?  Should `E_NUM_SLOT` be assumed to be part of `E_NUM`?  And what if it isn't?  When should the compiler emit an error that `E_NUM_SLOT` doesn't exist?  And on what line - does every use need to be tracked for future errors?
