### ISSUE TITLE
Sizeof for enums

### ISSUE THREAD

**Issue by Misiur** [Zeex/pawn#44]
I'm not certain how compiler handles enumerators, but sizeof doesn't bode well with hidden array sizes:
```pawn
enum E_TEST {
    RandomValue,
    StringValue[64]
};

new Anything[MAX_PLAYERS][E_TEST];

//...
sizeof Anything[0][StringValue]; //1 - it makes sense for compiler, but not for average user
```

**Comment by Arkshine** [comment]
You should use `sizeof Anything[][StringValue]`

**Comment by Misiur** [comment]
Ok, if Zeex says it's an unreasonable request I'll respect that. But very often I see people caught up with default values, for example strcat:
```pawn
native strcat(dest[], const source[], maxlength=sizeof dest);
```
So
```pawn
strcat(Anything[0][StringValue], "Dickbutt");
```
Simply fails.

**Comment by Arkshine** [comment]
There is a known issue with enum field and sizeof in this situation. It has been fixed in the Pawn 3.3.3930.

This should be similar to this : https://github.com/Arkshine/amxmodx/commit/a873066466286217dc2caa83b9259eae21fae406

**Comment by Zeex** [comment]
I was thinking... could this possibly break something? From the language point of view, it seems totally fine to return 1 for `sizeof Anything[0][StringValue]` since enums are just array indices IIRC.

@Y_Less what do you think?

**Comment by Y-Less** [comment]
I've always seen "1" here as the correct return.  This enum:

```pawn
enum X
{
    A,
    B[10],
    C
}
```

Is entirely equivalent to:

```pawn
enum X
{
    A,
    B,
    C = B + 10
}
```

Or:

```pawn
#define A X_tag:0
#define B X_tag:1
#define C X_tag:11
#define X X_tag:12
```

People would entirely expect "sizeof (B)" to return "1" there.  "B" is just a subset of "X", asking for its size is asking for the size of part of an array, not the whole array, and with this patch not even an element of the array.

Also, I have always said "enums are not arrays" - they are flattened by the compiler.  Doing:

```pawn
new arr[X];
arr[B][3];
```

Is just fancy syntax for:

```pawn
new arr[X];
arr[B + X_tag:3];
```

I didn't comment on this earlier, as if a majority of people think it should be different (as even the later official versions of PAWN seem to think it should) then who am I to argue?  But as I say, given everything here, I don't think it makes sense from a language point of view.  And since you asked directly...

**Comment by Arkshine** [comment]
I'm not sure we are talking about the same thing, but how is handle an enum internally is irrelevant to the fact that if you use an enum as a "structure", you would want to expect `sizeof B` returns `10` and not `1`. You're asking sizeof of an array not the index in the internal flat array.

**Comment by Zeex** [comment]
Indeed `sizeof Anything[0][StringValue]` doesn't compile outside of function calls. I was worried that this might have been used in some parts of YSI or perhaps other libraries.

I also looked this up in newer Pawn sources, couldn't find Pawn 3.3.3930 referenced in https://github.com/Arkshine/amxmodx/commit/a873066466286217dc2caa83b9259eae21fae406 but 3.3.4058 has it. I guess they knew what they were doing and had thought about possible backwards compatibility issues in advance.

**Comment by Y-Less** [comment]
I can't actually think of a place where it would cause issues, at least not for YSI.

**Comment by Zeex** [comment]
OK, then there are apparently no drawbacks, plus it's in the official Pawn. Let's leave it here.
