### ISSUE TITLE
Mutli-dimensional array initialisation completion

### ISSUE THREAD

**Issue by Y-Less** [Zeex/pawn#48]
It would be good if this was supported:

```pawn

new arr[10][20] = {{0, 1, ...}, ...};

```

Even better:

```pawn

new arr[10][20] = {{0, 1, 2, ...}, {0, 2, 4, ...}, ...};

```

Supporting the same increment rules across both dimensions.

**Comment by Zeex** [comment]
Just to clarity, what is arr[2] in your second example supposed to be? Should be it be `0, 4, 8, ...` or `0, 2, 4, ...` (i.e. same as arr[1]). In the current implementation it would be the latter.

**Comment by Y-Less** [comment]
I would think the first one.  If you want the second do:

```
new arr[10][20] = {{0, 1, 2, ...}, {0, 2, 4, ...}, {0, 2, 4, ...}, ...};
```

As with one dimension {0, 1, 1} to fill with almost all 1s using just the last two specified dimensions.

**Comment by Zeex** [comment]
Forgive me for the dumb question, but I'm still kind of trying to figure out how to calculate arr[2] via arr[0] and arr[1], so far I came up with this:

x = diff_2 - diff_1
arr[2] = { arr[1][0] + d, arr[1][1] + d, ...}

where diff_1 and diff_2 are the differences between the elements of arr[0] and arr[1] respectively. And the question is:

Does this look like the correct formula? I'm asking because this would yield arr[2] as `0, 3, 6` instead of `0,4, 8` as I wrote before.

**Comment by Y-Less** [comment]
I would expect {0, 3, 6}, since the increase is linear.

**Comment by Y-Less** [comment]
Actually, I would do it:

    arr[0][2] = arr[0][1] + diff(arr[0][0], arr[0][1]); // As in 1-d.
    arr[2][0] = arr[1][0] + diff(arr[0][0], arr[1][0]); // Same in the other dimension
    arr[2][1] = arr[1][1] + diff(arr[0][1], arr[1][1]);

Thus:

    arr[2][2] = arr[2][1] + diff(arr[2][0], arr[2][1]);

Which gives:

    {{0, 1, 2, 3, 4,...}, {0, 2, 4, 6, 8, ...},{0, 3, 6, 9,12, ...}{

**Comment by Zeex** [comment]
You mean it should do th increment across both rows and columns?

**Comment by Zeex** [comment]
Seems working now, if you need an executable for testing you can download it here:
https://ci.appveyor.com/project/Zeex/pawn/branch/master/artifacts

**Comment by Y-Less** [comment]
Awesome, thanks.
