### ISSUE TITLE
Cross compile for ARM CPUs

### ISSUE THREAD

**Issue by jtylr** [Zeex/pawn#628]
### Issue description:

Unsure if this is even a thing, but an ARM release (or instructions for an ARM build) would be greatly appreciated

**Comment by Y-Less** [comment]
It should be possible - the code is fairly portable C and the original system was designed to run on a wide range of platforms (at least, I know the AMX has a Thumb implementation, I'm less sure about the compiler itself).  As to HOW to do it, the setup uses CMake, and there is plenty of documentation about for that, but you might be somewhat on your own in terms of figuring it out because AFAIK no-one else has needed to figure it out.  But if you do, please do share the information for others' future reference.

**Comment by jtylr** [comment]
I'll give it a go, was hitting an issue earlier with the C itself, I'll have another try in a bit and maybe grab someone over discord.

**Comment by jtylr** [comment]
Spoke to Hual, for my use case (M1 Macbook, 64bit only) this won't work.
