### ISSUE TITLE
function name max length.. 32char?

### ISSUE THREAD

**Issue by tars-c** [Zeex/pawn#665]
Compiler Version: v3.10.10 Linux

In the next [fork](https://github.com/IllidanS4/pawn-compiler), the length limit for function names was updated to be closer to unlimited.

Does the community compiler currently being used by sampctl support this feature? (pawncc v3.10.10, max length 32)
Any thoughts on updating the next fork?

If the current community compiler doesn't have a limit on the length of function names, could you please leave a link to the relevant content to use the next feature?

I think the maximum length of a function name today is 32 characters too short.
I hope there is no limit on function names

**Comment by Y-Less** [comment]
Right, do people just think that we never thought of this?  That in 8 years no-one thought, oh lets just change this one simple define and solve all problems?

The problem isn't the compiler.  The compiler can have the limit changed easily at any moment, no problem.  The issue is the SA:MP server (yes, this isn't just used for SA:MP, but it somewhat is).  That ALSO has the function limit, so the compiler needs to conform to that because we can't increase the limit in the runtime.
