### ISSUE TITLE
Global Variable Initilization using functions - can fake global var init func calls at main - feature request

### ISSUE THREAD

**Issue by YashasSamaga** [Zeex/pawn#91]
Right now, the following code crashes the compiler if it is present outside functions.

`new globalvar = test(); `

Why not add a feature which automatically prefixes the appropriate code to main()?

For example, why not convert the following code 
` new globalvar = test(); main() { //CODE }`
to
` new globalvar; main() { globalvar = test(); //CODE }`

Of course, one can manually type the above code but it doesn't nice. Its useful for those who make includes. It sounds silly but I have a genuine reason why this would make things lot easier since I am writing an include which needs such a feature or I should expect the user to make a function call somewhere to initialize the variable.

**Comment by Y-Less** [comment]
That is what hooks are for - y_hooks or ALS.  Either are used to allow you to initiialise things before user code is called, without relying on them to call a function.

**Comment by YashasSamaga** [comment]
I don't get how I can use ALS/y_hooks in this situation. I am extremely picky about styling the syntax and hate to see ugly syntax (its my nature). I will show you want I actually want to do.

I make use of STL lists in PAWN using a plugin. I have defines which almost allows me to use the C++ template syntax. Here is one for the list, 

` #define list<%0>%1(%2) list:%1 = list:_list_local_Create(%2, .templateid = tagof(%0:))`

I like that syntax and I use it everywhere when I make local lists but if I have to make a global list then I am forced to use this ugly code in main(),

`List::lst.Initilize(0, 0, tagof(_fix_tagless_var));`

**Comment by oscar-broman** [comment]
Just make a public function, such as `_pfx_varname` then hook gamemode/fs init and search for all public functions with that prefix and invoke them.

Making an implicit addition to main sounds like a bad idea.

**Comment by YashasSamaga** [comment]
How do I distinguish between something which is declared outside a function and the ones which are inside? I might have to then add a new prefix/tag to differentiate between local & global lists.

**Comment by oscar-broman** [comment]
You can't. You'll have to make separate macros.

Those declared inside a function could simply use a static variable (aside from the other variable) that has value 1 if it has been initialized and 0 if not.

Why don't you just make a flag or enum field in the variable that states whether it has been initialized? You could check in any functions that use it and initialize it the first time it's used. That's how I usually get around these problems in Pawn - the fact that data structres are initialized to 0.

**Comment by Y-Less** [comment]
Lazy initialisation - I like it.

Anyway, there is no way to differentiate between locals and globals in the way you want.  At least if there is one I don't know it - and believe me I've run in to the same problem countless times.  I finally got around this problem in "y_iterate" with cunning variable names, so that if you don't call `Iter_Init()` on multi-dimensional arrays you get a warning like "Symbol is never used 'Init@IteratorName'".  That might not help you loads, but at least it tells users there's some small issue to fix.

Detecting brackets isn't hard in the general case, because you can do quite extensive things in macros.  However, there are more restrictions on what you can do in macros in variable declarations because the range of syntax you can use is less.  For most things, you use what I call "tag macros", which end up compiling as something like:

```pawn
x = _:has_brackets:has_quotes:42;
```

Each of which are both macros AND tag overrides, with a final "_:" to totally override the effects of the other tags in the final code.  If the macros match, their names are removed from the final code; if they don't the tags remain but have no effect.  You can do the same with some functions so you have macros and functions with the same name so if the macro matches the code vanishes, if it doesn't you are left with an extra function call.  I don't like using that method because it can leave you with a superfluous function call, but sometimes it can't be avoided.  On the other hand, tag overrides are totally removed in the final compilation, and the compiler can resolve basic maths as well to single results (see "y_stringhash" for what I believe is the best example of this, where thousands of lines of macros generating hundreds of characters of code finally compiles down to a single number in the final AMX).   Tag macros don't work in variable declarations because if you use more than one tag the compiler will complain (which does make sense - you are trying to tell the compiler what tag it is, it can't be multiple ones - PAWN doesn't have sum types), although you can have them on the values assigned.

For zero arguments, there are a few ways to do it.  I think for your issue the best solution is `%2-1+1`.  On its own that is perfectly legitimate and becomes zero (`-1+1`), with a parameter it results in the same as the parameter (e.g. `27-1+1`).

That was a little rambly because it was some of my thought process of solving your issue.  There are some subtle issues you have to be aware of.  For example, if you DON'T have brackets on your list's name, it is tricky to detect the end of the name - is it a comma or a semi-colon (or, of course, an open-bracket).  I should have written some generic macros for that, because I did keep re-doing it myself.  I've thought about it a lot, I can't think of a reliable way to do it in a variable declaration - sorry.  This is (part of) the reason why almost all my special variable declarations end with "<>" - it is a consistent end point you can detect.  So changing your syntax slightly, this is the best I've come up with:

```pawn
// Usage:
//   
//   new List:lst1<Float>; // Delaration, no initialisation.
//   new List:lst2<Float>(); // Initialisation.
//   

const list:LIST_INITIALISATION = list:0;
// Detect the double brackets and convert.
#define LIST_INITIALISATION%9LIST_REMOVE_ME(%1)(%2) list:_list_local_Create(%2-1+1, .templateid=tagof(%1:))

// If the "LIST_INITIALISATION" macro DOESN'T match, this second one will and
// will remove the extra data that the macro would otherwise need.  This will
// leave behind "= LIST_INITIALISATION", and thus use the global constant (0).
#define LIST_REMOVE_ME(%0)

// Detect and remove empty tag types (`_:` is (IIRC) always tag 0).
#define templateid=tagof(:) templateid=0

#define List:%0<%1> list:%0=LIST_INITIALISATION LIST_REMOVE_ME(%1)
```

Also, your `list:` tag should really be `List:`.  Tags that start with lower-case letters are "weak", tags that start with upper-case letters are "strong".  Weak tags can be used as integers anywhere you want an integer without the compiler complaining, strong tags will give a warning.  I suspect that you don't want list handles to be implicitly and silently converted to integers.
