### ISSUE TITLE
Public variable by name.

### ISSUE THREAD

**Issue by Dayvison** [Zeex/pawn#92]
How to call a public variable in pawn by name?
In the sdk is possible using **amx_FindPubVar**, in pawn is possible?

**Comment by Y-Less** [comment]
y_amx:

```pawn
new addr;
new value;
if (AMX_GetPubvarPointer(0, addr, "PubVarName"))
{
    value = AMX_Read(addr);
}
```

You can do it with amx_assembly as well.  I'm less sure on this code because IIRC amx_assembly returns addresses relative to the start of the AMX (which is how they are stored), while y_amx returns them relative to the start of the data segment (which is how they are needed for reading):

```pawn
new addr = GetPubVarAddressFromName("PubVarName");
new value;
if (addr != -1)
{
    value = ReadAmxMemory(addr);
}
```

Basically, yes it can be done.

If you want to search through lots of public variables, or read one a lot, I suggest y_amx - the "AMX_GetPubvarPointer" function can have the name excluded to be used in a loop, and the "AMX_Read" function self-inlines for speed (over engineered, but was fun to write, and stupidly fast).

If you only want to access one variable infrequently, use amx_assembly (which YSI now includes and uses anyway).  It has less startup overhead and is much simpler to use (plus avoids including YSI).

Or write your own assembly to do it - I wouldn't recommend that though when there are several libraries for it already.  I wouldn't have written y_amx if amx_assembly existed first, it is far more complete than the one I wrote to provide a few ad-hoc functions as I needed them.

**Comment by Dayvison** [comment]
Thanks Y_Less.
